import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { io } from "socket.io-client";
import type { Room, Result } from "../server/game";
import "./style.css";
import "./overrides.css";
import "./roll-effects.css";
import "./game-redesign.css";
import "./stick-sides.css";
import "./yut-three.css";
import "./piece-flight.css";
import "./hangame-inspired.css";
import "./video-inspired-layout.css";
import "./clean-theme.css";
import "./classic-board-theme.css";
import { YutThree } from "./YutThree";
const socket=io(); const labels:Record<Result,string>={DO:"도",GAE:"개",GEOL:"걸",YUT:"윷",MO:"모",BACKDO:"빽도",NAK:"낙"};
type Chat={name:string;text:string;at:number};
type MoveFx={id:string;owner:string;from:number;to:number;at:number};
function PieceFlight({fx,room,locations}:{fx?:MoveFx;room:Room;locations:[number,number][]}){const [at,setAt]=useState<[number,number]>();useEffect(()=>{if(!fx)return;const from=fx.from<0?0:fx.from,to=fx.to===99?0:fx.to;setAt(locations[from]??locations[0]);const frame=requestAnimationFrame(()=>setAt(locations[to]??locations[0]));const timer=window.setTimeout(()=>setAt(undefined),820);return()=>{cancelAnimationFrame(frame);window.clearTimeout(timer)}},[fx?.at]);if(!fx||!at)return null;const team=room.players.find(p=>p.id===fx.owner)?.team??0;return <div className={`piece-flight t${team}`} style={{left:`${at[0]}%`,top:`${at[1]}%`}}><span>{room.players.find(p=>p.id===fx.owner)?.name.slice(0,2)}</span></div>}
function StickRoll({data}:{data?:{result:Result;sticks:boolean[];rollId:number}}){return <div className={`sticks three-roll ${data?.result==="NAK"?"nak":""} ${data?.result==="BACKDO"?"backdo":""}`}><div className="throw-zone"><span>윷 던지기</span><div className="side-legend"><b><i className="legend-front"/>앞면</b><b><i className="legend-back"/>뒷면</b></div><YutThree data={data}/></div>{data&&<b key={data.rollId} className="result-pop">{labels[data.result]}<small>{data.result==="NAK"?"판 밖으로 떨어졌어요":data.result==="BACKDO"?"한 칸 뒤로 이동":""}</small></b>}</div>}
function PieceStatus({room}:{room:Room}){return <section className="piece-status" aria-label="말 현황">{room.players.map(p=>{const mine=room.pieces.filter(x=>x.owner===p.id),waiting=mine.filter(x=>x.pos===-1&&!x.finished).length,onBoard=mine.filter(x=>x.pos!==-1&&!x.finished).length;return <div key={p.id}><i className={`dot t${p.team}`}/><b>{p.name}</b><span className="piece-summary">대기 {waiting} · 판 {onBoard} · 완주 {p.finished}</span><span className="mini-pieces">{mine.map((piece,n)=><i key={piece.id} className={`mini-piece t${p.team} ${piece.finished?"finished":piece.pos!==-1?"on-board":""}`} title={`${n+1}번 말`}>👤<em>{n+1}</em></i>)}</span></div>})}</section>}
function ChatPanel({chats,text,setText,open,onToggle}:{chats:Chat[];text:string;setText:(value:string)=>void;open:boolean;onToggle:()=>void}){return <aside className={`chat-panel ${open?"open":"closed"}`}><div className="chat-heading"><h3>채팅</h3><button type="button" className="chat-toggle" onClick={onToggle} aria-expanded={open}>{open?"접기":"열기"}</button></div>{open&&<><div className="messages">{chats.map((c,i)=><p key={i}><b>{c.name}</b> {c.text}</p>)}</div><form onSubmit={e=>{e.preventDefault();if(text.trim()){socket.emit("chat",{text});setText("")}}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="메시지 입력"/><button>전송</button></form></>}</aside>}
function Board({room,me,onMove,rolling,fx,overlay}:{room:Room;me:string;onMove:(id:string,takeShortcut?:boolean)=>void;rolling:boolean;fx?:MoveFx;overlay?:React.ReactNode}){
 const [routePiece,setRoutePiece]=useState<string>();
 const cells=Array.from({length:29},(_,i)=>i);
 // 시작점이 오른쪽 아래가 되도록 윷판 전체를 좌우 대칭으로 배치한다.
 const locations:[number,number][]=[[92,92],[92,75],[92,58],[92,41],[92,24],[92,8],[75,8],[58,8],[41,8],[24,8],[8,8],[8,25],[8,42],[8,59],[8,76],[8,92],[25,92],[42,92],[59,92],[76,92],[75,25],[62,38],[50,50],[38,62],[25,75],[25,25],[38,38],[62,62],[75,75]];
 const canMove=!rolling&&room.pending.length>0&&room.players[room.turn]?.id===me;
 const amount=({DO:1,GAE:2,GEOL:3,YUT:4,MO:5,BACKDO:-1,NAK:0} as const)[room.pending[0] ?? "NAK"];
 const forward=(p:number,route?:"a"|"b")=>p===-1?1:p===19?99:p===5?(route==="a"?20:6):p===10?(route==="b"?25:11):p===20?21:p===21?22:p===22?(route==="b"?27:23):p===23?24:p===24?15:p===25?26:p===26?22:p===27?28:p===28?99:p+1;
 const backward=(p:number)=>p===-1?19:p===1?-1:p===20?5:p===21?20:p===22?21:p===23?22:p===24?23:p===25?10:p===26?25:p-1;
 const target=(pos:number,shortcut=false,route?:"a"|"b")=>{let at=pos,activeRoute=route;if(amount>0&&shortcut)activeRoute=pos===5?"a":"b";if(amount>0&&pos===22)activeRoute=shortcut?"b":"a";for(let i=0;i<Math.abs(amount);i++){at=amount>0?forward(at,activeRoute):backward(at);if(at===15||at===99)activeRoute=undefined;if(at===99)break}return at};
 const movable=room.pieces.filter(p=>canMove&&p.owner===me&&!p.finished);
 const waitingPieces=room.pieces.filter(p=>p.owner===me&&p.pos===-1&&!p.finished).sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true}));
 const nextWaiting=waitingPieces[0];
 const targets=new Set(movable.map(p=>{const t=target(p.pos,false,p.route);return t===-1?0:t}));
 const shortcutTargets=new Set(movable.filter(p=>amount>0&&[5,10,22].includes(p.pos)).map(p=>{const t=target(p.pos,true,p.route);return t===-1?0:t}));
 const pieceNumber=(id:string)=>Number(id.slice(id.lastIndexOf("-")+1))+1;
 const routePos=room.pieces.find(p=>p.id===routePiece)?.pos;
 return <div className={`board ${waitingPieces.length?"has-waiting":""}`}><span className="corner-label top-left">지름길</span><span className="corner-label top-right">지름길</span>{cells.map(n=>{const [x,y]=locations[n];const ps=room.pieces.filter(p=>p.pos===n&&!p.finished);const visible=ps.filter(p=>p.id===[p.id,...p.stackedWith].sort()[0]);const lit=targets.has(n),shortcutLit=shortcutTargets.has(n);return <div key={n} className={`cell ${[5,10,15].includes(n)?"corner":""} ${lit?"target":""} ${shortcutLit?"shortcut-target":""}`} style={{left:`${x}%`,top:`${y}%`}}>{visible.map(p=>{const selectable=canMove&&p.owner===me;const owner=room.players.find(x=>x.id===p.owner),count=p.stackedWith.length+1,canChoose=selectable&&amount>0&&[5,10,22].includes(p.pos);return <button key={p.id} title={`${owner?.name ?? "플레이어"}의 ${pieceNumber(p.id)}번 말${count>1?` · 업기 ×${count}`:""}`} onClick={()=>canChoose?setRoutePiece(p.id):onMove(p.id)} disabled={!selectable} className={`piece t${owner?.team??0} ${selectable?"selectable":""}`}><span className="piece-person" aria-hidden="true">👤</span><span className="piece-name">{owner?.name.slice(0,2)}</span><em>{pieceNumber(p.id)}</em>{count>1&&<b className="stack-count">×{count}</b>}</button>})}</div>})}{routePiece&&<div className="route-choice"><b>{routePos===22?"중앙에서 어느 길로 갈까요?":"어느 길로 갈까요?"}</b><div><button onClick={()=>{onMove(routePiece,false);setRoutePiece(undefined)}}>{routePos===22?"왼쪽 아래 길":"바깥길"}</button><button onClick={()=>{onMove(routePiece,true);setRoutePiece(undefined)}}>{routePos===22?"오른쪽 아래 길":"지름길"}</button></div><small>선택한 말만 이동합니다.</small></div>}{overlay}<PieceFlight fx={fx} room={room} locations={locations}/>{targets.has(99)&&<span className="finish target-finish">완주!</span>}<span className="start">출발 · 완주</span>{!overlay&&nextWaiting&&<div className={`waiting-dock t${room.players.find(p=>p.id===me)?.team??0} ${canMove&&amount!==0?"ready":""}`}><span>출발 대기 말 ×{waitingPieces.length}</span><button disabled={!canMove||amount===0} onClick={()=>onMove(nextWaiting.id)}><i aria-hidden="true">👤</i> {pieceNumber(nextWaiting.id)}번 말 출발</button><small>1번부터 순서대로 출발합니다</small></div>}</div>}
function App(){const [name,setName]=useState(localStorage.yutName||"");const [code,setCode]=useState("");const [mode,setMode]=useState<"solo"|"team">("team");const [joinTeam,setJoinTeam]=useState<0|1>(0);const [room,setRoom]=useState<Room>();const [me,setMe]=useState("");const [notice,setNotice]=useState("");const [chats,setChats]=useState<Chat[]>([]);const [text,setText]=useState("");const [chatOpen,setChatOpen]=useState(()=>typeof window==="undefined"?true:window.innerWidth>1000&&window.screen.width>760);const [rolling,setRolling]=useState(false);const [moveFx,setMoveFx]=useState<MoveFx>();
 useEffect(()=>{const receive=(r:Room)=>{setRoom(r);const mine=r.players.find(p=>p.id===socket.id);if(mine&&socket.id){setMe(socket.id);localStorage.yutSession=JSON.stringify({code:r.code,playerId:socket.id})}};const receiveMove=(fx:MoveFx)=>setMoveFx(fx);socket.on("room",receive);socket.on("chat",(c:Chat)=>setChats(v=>[...v.slice(-49),c]));socket.on("pieceMove",receiveMove);socket.on("connect",()=>{const saved=localStorage.yutSession;if(saved){try{const s=JSON.parse(saved);socket.emit("reconnectRoom",s,(x:{ok:boolean})=>{if(!x.ok)localStorage.removeItem("yutSession")})}catch{}}});return()=>{socket.off("room",receive);socket.off("chat");socket.off("pieceMove",receiveMove)}},[]);
 useEffect(()=>{if(!room?.lastRoll)return;setRolling(true);const timer=window.setTimeout(()=>setRolling(false),2750);return()=>window.clearTimeout(timer)},[room?.lastRoll?.rollId]);
 const action=(event:string,data:object={})=>socket.emit(event,data,(x:{ok:boolean;error?:string})=>{if(!x?.ok)setNotice(x?.error||"처리하지 못했습니다.")});
 if(!room)return <main className="landing"><h1>윷놀이터</h1><p>집에서도 함께 하는 실시간 윷놀이</p><input placeholder="닉네임" value={name} onChange={e=>setName(e.target.value)} /><div className="actions"><button onClick={()=>{if(!name.trim())return setNotice("닉네임을 입력하세요.");localStorage.yutName=name;socket.emit("create",{name,mode},(x:{ok:boolean;code?:string})=>x.ok&&setCode(x.code ?? "") )}}>방 만들기</button><select value={mode} onChange={e=>setMode(e.target.value as "solo"|"team")}><option value="team">팀전</option><option value="solo">개인전</option></select></div><button className="practice" onClick={()=>{if(!name.trim())return setNotice("닉네임을 입력하세요.");localStorage.yutName=name;socket.emit("create",{name,mode:"solo",practice:true},(x:{ok:boolean;error?:string})=>{if(!x.ok)return setNotice(x.error??"연습 방을 만들지 못했습니다.");socket.emit("start",{},(started:{ok:boolean;error?:string})=>!started?.ok&&setNotice(started?.error??"게임을 시작하지 못했습니다."))})}}>혼자 연습하기</button><div className="join"><input placeholder="방 코드" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/>{mode==="team"&&<select aria-label="입장 팀 선택" value={joinTeam} onChange={e=>setJoinTeam(Number(e.target.value) as 0|1)}><option value={0}>주황팀으로 입장</option><option value={1}>파랑팀으로 입장</option></select>}<button onClick={()=>{if(!name.trim())return setNotice("닉네임을 입력하세요.");localStorage.yutName=name;action("join",{code,name,team:joinTeam})}}>입장</button></div><small>{notice}</small></main>;
 const turn=room.players[room.turn],winnerText=room.mode==="team"?`${room.players.filter(p=>p.team===room.winner).map(p=>p.name).join(" · ")} 팀`:room.players[room.winner??0]?.name;
 const guide=room.status==="finished"?"게임이 끝났습니다. 다시 대결 투표를 해보세요.":rolling?"윷이 멈출 때까지 잠시 기다려 주세요.":room.pending.length>0&&turn?.id===me?`${labels[room.pending[0]]} 결과입니다. 빛나는 말 또는 출발 대기 말을 누르세요.`:turn?.id===me?"내 차례입니다. 윷 던지기를 눌러 주세요.":`${turn?.name ?? "상대"} 님이 움직이는 중입니다.`;
 const chatPanel=<ChatPanel chats={chats} text={text} setText={setText} open={chatOpen} onToggle={()=>setChatOpen(v=>!v)}/>;
 const gameBoard=<Board room={room} me={me} rolling={rolling} fx={moveFx} onMove={(pieceId,takeShortcut)=>action("move",{pieceId,takeShortcut})}/>;
 const lobbyOverlay=<section className="lobby-overlay"><span>대기실</span><strong>참가 인원 {room.players.length}/8명</strong><p>{room.practice?"혼자 연습을 시작하시겠습니까?":"친구가 들어오면 시작할 수 있습니다."}</p>{room.mode==="team"&&<div className="team-picker"><b>내 팀을 미리 선택하세요</b><div className="team-options">{([0,1] as const).map(team=><button key={team} className={`team-option t${team} ${room.players.find(p=>p.id===me)?.team===team?"chosen":""}`} onClick={()=>action("selectTeam",{team})}><strong>{team===0?"주황팀":"파랑팀"} <small>{room.players.filter(p=>p.team===team).length}/4</small></strong><span>{room.players.filter(p=>p.team===team).map(p=>p.name).join(" · ")||"아직 없음"}</span></button>)}</div></div>}{room.hostId===me?<><div className="lobby-buttons">{room.mode==="team"&&room.players.length>1&&<button className="team-shuffle" onClick={()=>action("shuffleTeams")}>팀 자동 섞기</button>}<button onClick={()=>action("start")}>{room.practice?"연습 시작":"게임 시작"}</button></div><small>{room.mode==="team"?"팀당 최대 4명 · 두 팀 모두 참가해야 시작할 수 있어요.":"방장이 게임을 시작합니다."}</small></>:<small>방장이 시작하기를 기다리는 중…</small>}</section>;
 const voteCount=room.rematchVotes?.length??0,voted=room.rematchVotes?.includes(me)??false;
 const winnerBanner=room.status==="finished"?<section className="winner-banner"><span>🏆 GAME OVER</span><strong>{winnerText} 승리!</strong><small>멋진 한 판이었습니다</small><div className="rematch-actions"><button disabled={voted} onClick={()=>action("rematchVote")}>{voted?"재대결 찬성 완료":"다시 하시겠습니까?"}</button><b>찬성 {voteCount}/{room.players.length}명</b><button className="new-room" onClick={()=>{localStorage.removeItem("yutSession");setChats([]);setRoom(undefined);setNotice("새 방을 만들어 다시 시작하세요.")}}>새 방 만들기</button></div></section>:null;
 const leaveRoom=()=>{if(!window.confirm("방에서 나갈까요? 진행 중인 게임에서는 재접속 전까지 내 턴이 자동으로 넘어갈 수 있습니다."))return;socket.emit("leaveRoom",{},()=>{localStorage.removeItem("yutSession");setChats([]);setRoom(undefined);setNotice("방에서 나왔습니다. 새 방을 만들거나 방 코드로 입장하세요.")})};
 return <main className="game"><header><h1>윷놀이터</h1><strong>방 코드: {room.code}</strong><span>{room.practice?"혼자 연습":room.mode==="team"?"팀전":"개인전"}</span><button className="leave-room" onClick={leaveRoom}>← 나가기</button></header><section className="players">{room.players.map((p,i)=><div key={p.id} className={i===room.turn?"active":""}><i className={`dot t${p.team}`}/>{p.name}{p.id===me?" (나)":""} · 완주 {p.finished}/4 {!p.connected&&" · 재접속 대기"}</div>)}</section>{winnerBanner}{room.status==="lobby"?<section className="play lobby-play"><div><Board room={room} me={me} rolling={false} fx={moveFx} onMove={()=>{}} overlay={lobbyOverlay}/></div>{chatPanel}</section>:<section className="play"><div><p className="turn">{room.status==="finished"?"게임 종료!":`${turn?.name} 님의 차례`}</p><p className="game-guide" aria-live="polite">{guide}</p><StickRoll data={room.lastRoll}/><PieceStatus room={room}/><button className="roll" disabled={rolling||turn?.id!==me||!!room.pending.length||room.status!=="playing"} onClick={()=>action("roll")}>윷 던지기</button>{rolling&&<p className="rolling-note">윷이 멈추는 중…</p>}{room.pending.length>0&&turn?.id===me&&!rolling&&<p>말을 눌러 <b>{labels[room.pending[0]]}</b>만큼 이동하세요.</p>}{gameBoard}</div>{chatPanel}</section>}<small className="notice">{notice}</small></main>}
createRoot(document.getElementById("root")!).render(<App/>);
