import test from "node:test"; import assert from "node:assert/strict"; import { createPieces, move, type Room } from "./game";
const room = (): Room => ({code:"TEST",hostId:"a",status:"playing",mode:"solo",players:[{id:"a",name:"A",team:0,connected:true,finished:0},{id:"b",name:"B",team:1,connected:true,finished:0}],pieces:[],turn:0,pending:[],extra:false});
test("말을 이동하고 상대 말을 잡는다", () => { const r=room(); createPieces(r); r.pieces.find(p=>p.id==="b-0")!.pos=1; move(r,"a-0","DO"); assert.equal(r.pieces.find(p=>p.id==="b-0")!.pos,-1); });
test("서로 다른 팀의 말은 팀전에서도 잡는다", () => { const r=room(); r.mode="team"; createPieces(r); r.pieces.find(p=>p.id==="b-0")!.pos=1; move(r,"a-0","DO"); assert.equal(r.pieces.find(p=>p.id==="b-0")!.pos,-1); assert.equal(r.extra,false); });
test("대기 말은 1번부터 차례로 출발한다", () => { const r=room(); createPieces(r); move(r,"a-0","DO"); r.turn=0; assert.throws(()=>move(r,"a-2","DO"),/1번부터/); move(r,"a-1","DO"); assert.equal(r.pieces.find(p=>p.id==="a-1")!.pos,1); });
for(const size of [2,3,4])test(`말 ${size}개를 업으면 대표 말이 함께 이동한다`,()=>{const r=room();createPieces(r);const pieces=Array.from({length:size},(_,index)=>r.pieces.find(piece=>piece.id===`a-${index}`)!);pieces[0].pos=2;for(let index=1;index<size;index++){r.turn=0;move(r,pieces[index].id,"GAE");assert.equal(pieces[index].pos,2)}const leader=pieces.at(-1)!;assert.equal(leader.stackedWith.length,size-1);assert.deepEqual(leader.stackedWith.sort(),pieces.slice(0,-1).map(piece=>piece.id).sort());r.turn=0;move(r,leader.id,"DO");for(const piece of pieces)assert.equal(piece.pos,3);});
test("윷은 추가 턴을 준다", () => { const r=room(); createPieces(r); move(r,"a-0","YUT"); assert.equal(r.turn,0); });
test("출발 빽도 뒤 개는 한 바퀴를 완주한다", () => { const r=room(); createPieces(r); move(r,"a-0","BACKDO"); assert.equal(r.pieces.find(p=>p.id==="a-0")!.pos,19); move(r,"b-0","DO"); move(r,"a-0","GAE"); assert.equal(r.pieces.find(p=>p.id==="a-0")!.finished,true); });
test("모서리 지름길과 중앙 대각선은 규칙 경로를 따른다", () => { const r=room(); createPieces(r); const p=r.pieces.find(p=>p.id==="a-0")!; p.pos=10; move(r,"a-0","GEOL",true); assert.equal(p.pos,22); assert.equal(p.route,"b"); move(r,"b-0","DO"); move(r,"a-0","GAE"); assert.equal(p.pos,28); assert.equal(p.route,"b"); });
