import express from "express"; import path from "node:path"; import { createServer } from "node:http"; import { Server } from "socket.io"; import { createPieces, current, move, previewMove, restartRound, roll, type Room } from "./game";
const app=express(), http=createServer(app), io=new Server(http,{cors:{origin:true}}); app.get("/health",(_,r)=>r.json({ok:true}));
// Render에서는 이 서버가 Vite가 만든 화면과 WebSocket을 같은 주소에서 제공한다.
app.use(express.static(path.resolve("dist"))); app.get(/.*/,(_,r)=>r.sendFile(path.resolve("dist/index.html")));
const rooms=new Map<string,Room>(); const sessions=new Map<string,{room:string;player:string;role:"player"|"spectator"}>();
const code=()=>Math.random().toString(36).slice(2,7).toUpperCase(); const publish=(r:Room)=>io.to(r.code).emit("room",r);
let eventSequence=0;
const record=(r:Room,kind:NonNullable<Room["events"]>[number]["kind"],text:string,team?:number)=>{const events=r.events??=[];events.push({id:++eventSequence,kind,text,team,at:Date.now()});if(events.length>40)events.splice(0,events.length-40);};
const disconnectTimers=new Map<string,ReturnType<typeof setTimeout>>();
const autoTimers=new Map<string,ReturnType<typeof setTimeout>>();
// The animation lasts 3.2 seconds.  This server-side lock is authoritative so
// a mobile double-tap cannot spend a Yut/Mo extra throw before it is shown.
const rollLocks=new Map<string,number>();
const ROLL_LOCK_MS=3400;
const nextTurn=(r:Room)=>{r.turn=(r.turn+1)%r.players.length;const next=current(r);if(next)record(r,"system",`${next.name} 님 차례입니다.`,next.team)};
// 종료 후 준비 완료한 사람만 다음 판의 플레이어로 남긴다. 준비하지 않은
// 기존 플레이어는 방을 나가지 않아도 관전자 자리에서 다음 판을 볼 수 있다.
const startReadyRematch=(r:Room)=>{const readyIds=new Set((r.rematchVotes??[]).filter(id=>r.players.some(player=>player.id===id&&player.connected)));const ready=r.players.filter(player=>readyIds.has(player.id));if(!readyIds.has(r.hostId))throw new Error("방장도 준비 완료한 뒤 게임을 시작할 수 있습니다.");if(ready.length<2)throw new Error("준비 완료한 플레이어가 2명 이상 필요합니다.");if(r.mode==="team"&&![0,1].every(team=>ready.some(player=>player.team===team)))throw new Error("팀전은 준비 완료 인원에 두 팀이 모두 있어야 합니다.");const waiting=r.players.filter(player=>!readyIds.has(player.id));waiting.forEach(player=>{if(!r.spectators.some(observer=>observer.id===player.id))r.spectators.push({id:player.id,name:player.name,connected:player.connected});const session=sessions.get(player.id);if(session)session.role="spectator"});r.players=ready;r.rematchVotes=[];restartRound(r);const first=current(r);if(first)record(r,"system",`${first.name} 님 차례입니다.`,first.team)};
const markDisconnected=(r:Room,playerId:string)=>{const p=r.players.find(x=>x.id===playerId);if(!p||!p.connected)return;p.connected=false;p.auto=true;p.disconnectedAt=Date.now();record(r,"system",`${p.name} 님의 연결이 끊겨 자동 진행으로 전환했습니다.`,p.team);publish(r);scheduleAuto(r);if(r.status!=="playing"||current(r)?.id!==playerId)return;const key=`${r.code}:${playerId}`;if(disconnectTimers.has(key))return;disconnectTimers.set(key,setTimeout(()=>{disconnectTimers.delete(key);const waiting=r.players.find(x=>x.id===playerId);if(r.status==="playing"&&waiting&&!waiting.connected&&current(r)?.id===playerId){r.pending=[];r.extraThrows=0;r.extra=false;r.stackOffer=undefined;nextTurn(r);publish(r);scheduleAuto(r)}},30000));};
const completeMove=(r:Room,pieceId:string,takeShortcut:boolean,resultIndex:number,stackWithId?:string)=>{const actor=current(r),before=new Map(r.pieces.map(p=>[p.id,p.pos])),beforeFinished=actor.finished,beforeStacked=r.pieces.find(p=>p.id===pieceId)?.stackedWith.length??0,captureAt=r.lastCapture?.at,result=r.pending[resultIndex];if(!result)throw new Error("선택한 결과가 없습니다.");move(r,pieceId,result,!!takeShortcut,stackWithId);r.pending.splice(resultIndex,1);r.stackOffer=undefined;const moved=r.pieces.find(p=>p.id===pieceId),captured=r.lastCapture?.at!==captureAt;if(captured){r.extraThrows++;const victims=(r.lastCapture?.owners??[]).map(id=>r.players.find(player=>player.id===id)?.name).filter(Boolean).join(" · ")||"상대";record(r,"capture",`${actor.name} 님이 ${victims} 님의 말 ${r.lastCapture?.count}개를 잡았습니다!`,actor.team)}if((beforeStacked===0&&moved&&moved.stackedWith.length>0)||stackWithId)record(r,"move",`${actor.name} 님이 말 ${moved?.stackedWith.length?moved.stackedWith.length+1:2}개를 업었습니다.`,actor.team);if(actor.finished>beforeFinished)record(r,"finish",`${actor.name} 님이 완주했습니다.`,actor.team);const noPieceOnBoard=r.pieces.filter(piece=>piece.owner===actor.id&&!piece.finished).every(piece=>piece.pos===-1),onlyBackdos=r.pending.length>0&&r.pending.every(value=>value==="BACKDO");if(r.status==="finished"){const winner=r.mode==="team"?r.players.filter(p=>p.team===r.winner).map(p=>p.name).join(" · "):r.players[r.winner??0]?.name;record(r,"finish",`${winner} 승리!`,r.mode==="team"?r.winner:actor.team)}else if(noPieceOnBoard&&onlyBackdos){r.pending=[];record(r,"system",`${actor.name} 님의 말이 판 위에 없어 남은 빽도는 무효입니다.`,actor.team);nextTurn(r)}else if(r.pending.length===0&&r.extraThrows===0)nextTurn(r);if(moved)io.to(r.code).emit("pieceMove",{id:moved.id,owner:moved.owner,from:before.get(moved.id)??-1,to:moved.finished?99:moved.pos,at:Date.now()});publish(r);};
const scheduleAuto=(r:Room,delay=3600)=>{const player=current(r),key=player&&`${r.code}:${player.id}`;if(!player||!key||r.status!=="playing"||!player.auto)return;const old=autoTimers.get(key);if(old)clearTimeout(old);autoTimers.set(key,setTimeout(()=>{autoTimers.delete(key);const actor=current(r);if(!actor||actor.id!==player.id||!actor.auto||r.status!=="playing")return;if(r.pending.length>0&&r.extraThrows===0){const result=r.pending[0],candidates=r.pieces.filter(piece=>piece.owner===actor.id&&!piece.finished&&!piece.carriedBy&&(result==="BACKDO"?piece.pos!==-1:true)).sort((a,b)=>(a.pos===-1?1:0)-(b.pos===-1?1:0)||a.id.localeCompare(b.id));const selected=candidates[0];if(selected){try{completeMove(r,selected.id,false,0)}catch{r.pending=[];nextTurn(r);publish(r)}}else{r.pending=[];nextTurn(r);publish(r)}scheduleAuto(r);return}const value={...roll(),rollId:Date.now()},label:Record<typeof value.result,string>={DO:"도",GAE:"개",GEOL:"걸",YUT:"윷",MO:"모",BACKDO:"빽도",NAK:"낙"};if(r.extraThrows>0)r.extraThrows--;r.lastRoll=value;record(r,"roll",`${actor.name} · ${label[value.result]}`,actor.team);const noPiece=value.result==="BACKDO"&&r.pending.length===0&&r.pieces.filter(piece=>piece.owner===actor.id&&!piece.finished).every(piece=>piece.pos===-1);if(value.result==="NAK"||noPiece){r.pending=[];r.extraThrows=0;if(noPiece)record(r,"system",`${actor.name} 님의 말이 판 위에 없어 빽도는 무효입니다.`,actor.team);nextTurn(r)}else{r.pending.push(value.result);if(value.result==="YUT"||value.result==="MO")r.extraThrows++}io.to(r.code).emit("roll",value);publish(r);scheduleAuto(r)},delay));};
io.on("connection",socket=>{
  socket.on("checkRoom",({code:c},done)=>{const r=rooms.get(String(c??"").trim().toUpperCase());done?.({ok:!!r&&!r.practice&&((r.status==="lobby"&&r.players.length<8)||r.spectators.length<50)});});
  socket.on("create",({name,mode,practice},done)=>{ const c=code(), r:Room={code:c,hostId:socket.id,status:"lobby",mode,practice:!!practice,players:[{id:socket.id,name,team:0,connected:true,finished:0}],spectators:[],pieces:[],turn:0,pending:[],extraThrows:0,events:[],extra:false,rematchVotes:[]}; rooms.set(c,r); socket.join(c); sessions.set(socket.id,{room:c,player:socket.id,role:"player"}); done({ok:true,code:c}); publish(r); });
  socket.on("join",({code:c,name,team,spectate},done)=>{ const roomCode=String(c??"").trim().toUpperCase(),r=rooms.get(roomCode); if(!r||r.practice)return done({ok:false,error:"입장할 수 없는 방입니다."}); if(spectate){if(r.spectators.length>=50)return done({ok:false,error:"관전자 인원이 가득 찼습니다."});r.spectators.push({id:socket.id,name:String(name??"관전자").trim().slice(0,16)||"관전자",connected:true});socket.join(roomCode);sessions.set(socket.id,{room:roomCode,player:socket.id,role:"spectator"});done({ok:true,code:roomCode,spectate:true});publish(r);return}if(r.status!=="lobby"||r.players.length>=8)return done({ok:false,error:"입장할 수 없는 방입니다. 진행 중인 방은 관전으로 입장하세요."}); const requested=team===0||team===1?team:undefined, counts=[0,1].map(t=>r.players.filter(p=>p.team===t).length); const assigned=requested!==undefined&&counts[requested]<4?requested:counts[0]<=counts[1]?0:1; r.players.push({id:socket.id,name,team:assigned,connected:true,finished:0}); socket.join(roomCode); sessions.set(socket.id,{room:roomCode,player:socket.id,role:"player"}); done({ok:true,code:roomCode}); publish(r); });
  socket.on("changeRole",({role,team},done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),canChange=!!r&&(r.status==="lobby"||r.status==="finished");if(!r||!s||!canChange||r.practice||(role!=="player"&&role!=="spectator"))return done?.({ok:false,error:"대기실 또는 게임 종료 뒤에만 역할을 바꿀 수 있습니다."});if(role===s.role)return done?.({ok:true});if(role==="player"){if(r.players.length>=8)return done?.({ok:false,error:"참가 인원이 이미 8명입니다."});const observer=r.spectators.find(item=>item.id===socket.id);if(!observer)return done?.({ok:false,error:"관전자 정보를 찾을 수 없습니다."});const requested=team===0||team===1?team:undefined,counts=[0,1].map(value=>r.players.filter(player=>player.team===value).length),assigned=requested!==undefined&&counts[requested]<4?requested:counts[0]<=counts[1]?0:1;r.spectators=r.spectators.filter(item=>item.id!==socket.id);r.players.push({id:socket.id,name:observer.name,team:assigned,connected:true,finished:0});s.role="player";publish(r);return done?.({ok:true})}if(r.players.length<=1)return done?.({ok:false,error:"마지막 참가자는 관전으로 전환할 수 없습니다."});const player=r.players.find(item=>item.id===socket.id);if(!player)return done?.({ok:false,error:"참가자 정보를 찾을 수 없습니다."});r.players=r.players.filter(item=>item.id!==socket.id);r.spectators.push({id:socket.id,name:player.name,connected:true});r.rematchVotes=(r.rematchVotes??[]).filter(id=>id!==socket.id);if(r.hostId===socket.id)r.hostId=r.players[0].id;s.role="spectator";publish(r);done?.({ok:true});});
  socket.on("start",(_,done)=>{ const s=sessions.get(socket.id),r=s&&rooms.get(s.room); const teamsReady=!r||r.mode!=="team"||([0,1].every(t=>r.players.some(p=>p.team===t))); if(!r||r.hostId!==socket.id||(!r.practice&&r.players.length<2)||!teamsReady)return done?.({ok:false,error:r?.mode==="team"?"두 팀에 한 명 이상씩 배정한 뒤 시작하세요.":"2명 이상 필요하며 방장만 시작할 수 있습니다."}); r.status="playing";createPieces(r);const first=current(r);if(first)record(r,"system",`${first.name} 님 차례입니다.`,first.team);publish(r); });
  socket.on("selectTeam",({team},done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),p=r?.players.find(x=>x.id===socket.id),canPick=!!r&&(r.status==="lobby"||r.status==="finished");if(!r||!p||!canPick||r.mode!=="team"||(team!==0&&team!==1))return done?.({ok:false,error:"대기실 또는 게임 종료 뒤에만 팀을 선택할 수 있습니다."});if(p.team!==team&&r.players.filter(x=>x.team===team).length>=4)return done?.({ok:false,error:"이 팀은 이미 4명입니다."});p.team=team;publish(r);done?.({ok:true});});
  socket.on("shuffleTeams",(_,done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),canShuffle=!!r&&(r.status==="lobby"||r.status==="finished");if(!r||r.hostId!==socket.id||!canShuffle||r.mode!=="team")return done?.({ok:false,error:"팀전 대기실 또는 게임 종료 뒤의 방장만 팀을 섞을 수 있습니다."});const shuffled=[...r.players];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}shuffled.forEach((p,i)=>p.team=i%2);publish(r);done?.({ok:true});});
  socket.on("roll",(_,done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),now=Date.now();if(!r||r.status!=="playing"||current(r).id!==socket.id||(r.pending.length>0&&r.extraThrows===0)||r.stackOffer)return done?.({ok:false,error:"먼저 쌓인 결과를 이동하거나, 추가 던지기를 사용해 주세요."});if((rollLocks.get(r.code)??0)>now)return done?.({ok:false,error:"윷이 멈추는 중입니다. 결과가 나온 뒤 다시 던져 주세요."});rollLocks.set(r.code,now+ROLL_LOCK_MS);const player=current(r),value={...roll(),rollId:now},label:Record<typeof value.result,string>={DO:"도",GAE:"개",GEOL:"걸",YUT:"윷",MO:"모",BACKDO:"빽도",NAK:"낙"};if(r.extraThrows>0)r.extraThrows--;r.lastRoll=value;record(r,"roll",`${player.name} · ${label[value.result]}`,player.team);const noPieceOnBoard=value.result==="BACKDO"&&r.pending.length===0&&r.pieces.filter(piece=>piece.owner===player.id&&!piece.finished).every(piece=>piece.pos===-1);if(value.result==="NAK"||noPieceOnBoard){r.pending=[];r.extraThrows=0;if(noPieceOnBoard)record(r,"system",`${player.name} 님의 말이 판 위에 없어 빽도는 무효입니다.`,player.team);nextTurn(r)}else{r.pending.push(value.result);if(value.result==="YUT"||value.result==="MO")r.extraThrows++}io.to(r.code).emit("roll",value);publish(r);scheduleAuto(r);done?.({ok:true});});
  socket.on("move",({pieceId,takeShortcut,resultIndex},done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),index=Number.isInteger(resultIndex)?resultIndex:0;if(!r||current(r).id!==socket.id||!r.pending[index]||r.extraThrows>0||r.stackOffer)return done?.({ok:false,error:r?.extraThrows?"추가 던지기 기회를 먼저 모두 사용해 주세요.":"이동할 수 없습니다."});try{const actor=current(r),landing=previewMove(r,pieceId,r.pending[index],!!takeShortcut),host=r.mode==="team"&&landing.to!==99?r.pieces.find(p=>p.pos===landing.to&&!p.finished&&p.owner!==actor.id&&!p.carriedBy&&r.players.find(x=>x.id===p.owner)?.team===actor.team):undefined;if(host){r.stackOffer={playerId:actor.id,pieceId,hostPieceId:host.id,takeShortcut:!!takeShortcut,resultIndex:index};publish(r);done?.({ok:true});return}completeMove(r,pieceId,!!takeShortcut,index);scheduleAuto(r)}catch(e){done?.({ok:false,error:(e as Error).message})}});
  socket.on("stackDecision",({accept},done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),offer=r?.stackOffer;if(!r||!offer||offer.playerId!==socket.id||current(r).id!==socket.id||!r.pending[offer.resultIndex]||r.extraThrows>0)return done?.({ok:false,error:"업기 선택을 할 수 없습니다."});try{completeMove(r,offer.pieceId,offer.takeShortcut,offer.resultIndex,accept?offer.hostPieceId:undefined);scheduleAuto(r);done?.({ok:true})}catch(e){done?.({ok:false,error:(e as Error).message})}});
  socket.on("setAuto",({enabled},done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),p=r?.players.find(player=>player.id===socket.id);if(!r||!p||!p.connected)return done?.({ok:false,error:"복귀한 참가자만 자동 진행을 변경할 수 있습니다."});p.auto=!!enabled;record(r,"system",`${p.name} 님이 자동 진행을 ${p.auto?"켰습니다":"껐습니다"}.`,p.team);const key=`${r.code}:${p.id}`,timer=autoTimers.get(key);if(!p.auto&&timer){clearTimeout(timer);autoTimers.delete(key)}publish(r);if(p.auto)scheduleAuto(r);done?.({ok:true});});
  socket.on("rematchVote",(_,done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),p=r?.players.find(player=>player.id===socket.id);if(!r||!p||r.status!=="finished")return done?.({ok:false,error:"참가자만 게임이 끝난 뒤 준비 완료할 수 있습니다."});r.rematchVotes ??= [];if(!r.rematchVotes.includes(socket.id)){r.rematchVotes.push(socket.id);record(r,"system",`${p.name} 님이 다음 게임 준비를 완료했습니다.`,p.team)}publish(r);done?.({ok:true});});
  socket.on("startReadyRematch",(_,done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room);if(!r||r.status!=="finished"||r.hostId!==socket.id)return done?.({ok:false,error:"게임 종료 뒤 방장만 다음 게임을 시작할 수 있습니다."});try{startReadyRematch(r);publish(r);done?.({ok:true})}catch(error){done?.({ok:false,error:(error as Error).message})}});
  socket.on("leaveRoom",(_,done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room);if(!r)return done?.({ok:true});socket.leave(r.code);sessions.delete(socket.id);if(s?.role==="spectator"){r.spectators=r.spectators.filter(observer=>observer.id!==socket.id);publish(r);done?.({ok:true});return}if(r.status==="lobby"){r.players=r.players.filter(p=>p.id!==socket.id);if(r.hostId===socket.id&&r.players[0])r.hostId=r.players[0].id;if(!r.players.length)rooms.delete(r.code);else publish(r)}else markDisconnected(r,socket.id);done?.({ok:true});});
  socket.on("chat",({text})=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),sender=r&&(r.players.find(p=>p.id===socket.id)??r.spectators.find(observer=>observer.id===socket.id));if(r&&sender&&text?.trim())io.to(r.code).emit("chat",{name:sender.name,playerId:socket.id,text:text.trim().slice(0,300),at:Date.now()})});
  socket.on("reconnectRoom",({code:c,playerId},done)=>{const r=rooms.get(c),p=r?.players.find(x=>x.id===playerId),observer=r?.spectators.find(x=>x.id===playerId);if(!r||(!p&&!observer))return done({ok:false});if(observer&&!p){observer.id=socket.id;observer.connected=true;socket.join(c);sessions.set(socket.id,{room:c,player:socket.id,role:"spectator"});done({ok:true,code:c,spectate:true});publish(r);return}p!.id=socket.id;p!.connected=true;p!.auto=false;p!.disconnectedAt=undefined;record(r,"system",`${p!.name} 님이 복귀해 자동 진행을 껐습니다.`,p!.team);const key=`${r.code}:${playerId}`,timer=disconnectTimers.get(key);if(timer){clearTimeout(timer);disconnectTimers.delete(key)}if(r.hostId===playerId)r.hostId=socket.id;r.pieces.forEach(x=>{if(x.owner===playerId)x.owner=socket.id});const offer=r.stackOffer;if(offer&&offer.playerId===playerId)offer.playerId=socket.id;if(r.rematchVotes)r.rematchVotes=r.rematchVotes.map(id=>id===playerId?socket.id:id);socket.join(c);sessions.set(socket.id,{room:c,player:socket.id,role:"player"});done({ok:true,code:c});publish(r)});
  socket.on("disconnect",()=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room);if(r){if(s?.role==="spectator"){r.spectators=r.spectators.filter(observer=>observer.id!==socket.id);publish(r)}else markDisconnected(r,socket.id)}sessions.delete(socket.id)});
}); const port=Number(process.env.PORT ?? 3001); http.listen(port,"0.0.0.0",()=>console.log(`Yut server: http://localhost:${port}`));
