import express from "express"; import path from "node:path"; import { createServer } from "node:http"; import { Server } from "socket.io"; import { createPieces, current, move, previewMove, restartRound, roll, type Room } from "./game";
const app=express(), http=createServer(app), io=new Server(http,{cors:{origin:true}}); app.get("/health",(_,r)=>r.json({ok:true}));
// Render에서는 이 서버가 Vite가 만든 화면과 WebSocket을 같은 주소에서 제공한다.
app.use(express.static(path.resolve("dist"))); app.get(/.*/,(_,r)=>r.sendFile(path.resolve("dist/index.html")));
const rooms=new Map<string,Room>(); const sessions=new Map<string,{room:string;player:string}>();
const code=()=>Math.random().toString(36).slice(2,7).toUpperCase(); const publish=(r:Room)=>io.to(r.code).emit("room",r);
const record=(r:Room,kind:NonNullable<Room["events"]>[number]["kind"],text:string,team?:number)=>{const events=r.events??=[];events.push({id:Date.now()+Math.floor(Math.random()*1000),kind,text,team,at:Date.now()});if(events.length>40)events.splice(0,events.length-40);};
const disconnectTimers=new Map<string,ReturnType<typeof setTimeout>>();
const markDisconnected=(r:Room,playerId:string)=>{const p=r.players.find(x=>x.id===playerId);if(!p||!p.connected)return;p.connected=false;p.disconnectedAt=Date.now();record(r,"system",`${p.name} 님이 연결이 끊겼습니다.`,p.team);publish(r);if(r.status!=="playing"||current(r)?.id!==playerId)return;const key=`${r.code}:${playerId}`;if(disconnectTimers.has(key))return;disconnectTimers.set(key,setTimeout(()=>{disconnectTimers.delete(key);const waiting=r.players.find(x=>x.id===playerId);if(r.status==="playing"&&waiting&&!waiting.connected&&current(r)?.id===playerId){r.pending=[];r.extra=false;r.turn=(r.turn+1)%r.players.length;const next=current(r);if(next)record(r,"system",`${next.name} 님 차례입니다.`,next.team);publish(r)}},30000));};
const completeMove=(r:Room,pieceId:string,takeShortcut:boolean,stackWithId?:string)=>{const actor=current(r),before=new Map(r.pieces.map(p=>[p.id,p.pos])),beforeFinished=actor.finished,beforeStacked=r.pieces.find(p=>p.id===pieceId)?.stackedWith.length??0,captureAt=r.lastCapture?.at,result=r.pending[0];move(r,pieceId,result,!!takeShortcut,stackWithId);r.pending.shift();r.stackOffer=undefined;const moved=r.pieces.find(p=>p.id===pieceId);if(r.lastCapture?.at!==captureAt)record(r,"capture",`${actor.name} 님이 말 ${r.lastCapture?.count}개를 잡았습니다!`,actor.team);if((beforeStacked===0&&moved&&moved.stackedWith.length>0)||stackWithId)record(r,"move",`${actor.name} 님이 말 ${moved?.stackedWith.length?moved.stackedWith.length+1:2}개를 업었습니다.`,actor.team);if(actor.finished>beforeFinished)record(r,"finish",`${actor.name} 님이 완주했습니다.`,actor.team);if(r.status==="finished"){const winner=r.mode==="team"?r.players.filter(p=>p.team===r.winner).map(p=>p.name).join(" · "):r.players[r.winner??0]?.name;record(r,"finish",`${winner} 승리!`,r.mode==="team"?r.winner:actor.team)}else{const next=current(r);if(next)record(r,"system",`${next.name} 님 차례입니다.`,next.team)}if(moved)io.to(r.code).emit("pieceMove",{id:moved.id,owner:moved.owner,from:before.get(moved.id)??-1,to:moved.finished?99:moved.pos,at:Date.now()});publish(r);};
io.on("connection",socket=>{
  socket.on("create",({name,mode,practice},done)=>{ const c=code(), r:Room={code:c,hostId:socket.id,status:"lobby",mode,practice:!!practice,players:[{id:socket.id,name,team:0,connected:true,finished:0}],pieces:[],turn:0,pending:[],events:[],extra:false,rematchVotes:[]}; rooms.set(c,r); socket.join(c); sessions.set(socket.id,{room:c,player:socket.id}); done({ok:true,code:c}); publish(r); });
  socket.on("join",({code:c,name,team},done)=>{ const r=rooms.get(c); if(!r||r.practice||r.status!=="lobby"||r.players.length>=8)return done({ok:false,error:"입장할 수 없는 방입니다."}); const requested=team===0||team===1?team:undefined, counts=[0,1].map(t=>r.players.filter(p=>p.team===t).length); const assigned=requested!==undefined&&counts[requested]<4?requested:counts[0]<=counts[1]?0:1; r.players.push({id:socket.id,name,team:assigned,connected:true,finished:0}); socket.join(c); sessions.set(socket.id,{room:c,player:socket.id}); done({ok:true,code:c}); publish(r); });
  socket.on("start",(_,done)=>{ const s=sessions.get(socket.id),r=s&&rooms.get(s.room); const teamsReady=!r||r.mode!=="team"||([0,1].every(t=>r.players.some(p=>p.team===t))); if(!r||r.hostId!==socket.id||(!r.practice&&r.players.length<2)||!teamsReady)return done?.({ok:false,error:r?.mode==="team"?"두 팀에 한 명 이상씩 배정한 뒤 시작하세요.":"2명 이상 필요하며 방장만 시작할 수 있습니다."}); r.status="playing";createPieces(r);const first=current(r);if(first)record(r,"system",`${first.name} 님 차례입니다.`,first.team);publish(r); });
  socket.on("selectTeam",({team},done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),p=r?.players.find(x=>x.id===socket.id);if(!r||!p||r.status!=="lobby"||r.mode!=="team"||(team!==0&&team!==1))return done?.({ok:false,error:"팀전 대기실에서만 팀을 선택할 수 있습니다."});if(p.team!==team&&r.players.filter(x=>x.team===team).length>=4)return done?.({ok:false,error:"이 팀은 이미 4명입니다."});p.team=team;publish(r);done?.({ok:true});});
  socket.on("shuffleTeams",(_,done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room);if(!r||r.hostId!==socket.id||r.status!=="lobby"||r.mode!=="team")return done?.({ok:false,error:"팀전 대기실의 방장만 팀을 섞을 수 있습니다."});const shuffled=[...r.players];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}shuffled.forEach((p,i)=>p.team=i%2);publish(r);done?.({ok:true});});
  socket.on("roll",(_,done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room);if(!r||r.status!=="playing"||current(r).id!==socket.id||r.pending.length)return done?.({ok:false,error:"지금은 던질 수 없습니다."});const player=current(r),value={...roll(),rollId:Date.now()},label:Record<typeof value.result,string>={DO:"도",GAE:"개",GEOL:"걸",YUT:"윷",MO:"모",BACKDO:"빽도",NAK:"낙"};r.lastRoll=value;record(r,"roll",`${player.name} · ${label[value.result]}`,player.team);if(value.result==="NAK"){r.turn=(r.turn+1)%r.players.length;const next=current(r);if(next)record(r,"system",`${next.name} 님 차례입니다.`,next.team)}else r.pending.push(value.result);io.to(r.code).emit("roll",value);publish(r);});
  socket.on("move",({pieceId,takeShortcut},done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room);if(!r||current(r).id!==socket.id||!r.pending.length||r.stackOffer)return done?.({ok:false,error:"이동할 수 없습니다."});try{const actor=current(r),landing=previewMove(r,pieceId,r.pending[0],!!takeShortcut),host=r.mode==="team"&&landing.to!==99?r.pieces.find(p=>p.pos===landing.to&&!p.finished&&p.owner!==actor.id&&!p.carriedBy&&r.players.find(x=>x.id===p.owner)?.team===actor.team):undefined;if(host){r.stackOffer={playerId:actor.id,pieceId,hostPieceId:host.id,takeShortcut:!!takeShortcut};publish(r);done?.({ok:true});return}completeMove(r,pieceId,!!takeShortcut)}catch(e){done?.({ok:false,error:(e as Error).message})}});
  socket.on("stackDecision",({accept},done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room),offer=r?.stackOffer;if(!r||!offer||offer.playerId!==socket.id||current(r).id!==socket.id||!r.pending.length)return done?.({ok:false,error:"업기 선택을 할 수 없습니다."});try{completeMove(r,offer.pieceId,offer.takeShortcut,accept?offer.hostPieceId:undefined);done?.({ok:true})}catch(e){done?.({ok:false,error:(e as Error).message})}});
  socket.on("rematchVote",(_,done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room);if(!r||r.status!=="finished")return done?.({ok:false,error:"게임이 끝난 뒤에만 투표할 수 있습니다."});r.rematchVotes ??= [];if(!r.rematchVotes.includes(socket.id))r.rematchVotes.push(socket.id);if(r.rematchVotes.length===r.players.length){restartRound(r);const first=current(r);if(first)record(r,"system",`${first.name} 님 차례입니다.`,first.team)}publish(r);done?.({ok:true});});
  socket.on("leaveRoom",(_,done)=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room);if(!r)return done?.({ok:true});socket.leave(r.code);sessions.delete(socket.id);if(r.status==="lobby"){r.players=r.players.filter(p=>p.id!==socket.id);if(r.hostId===socket.id&&r.players[0])r.hostId=r.players[0].id;if(!r.players.length)rooms.delete(r.code);else publish(r)}else markDisconnected(r,socket.id);done?.({ok:true});});
  socket.on("chat",({text})=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room);if(r&&text?.trim())io.to(r.code).emit("chat",{name:r.players.find(p=>p.id===socket.id)?.name,text:text.trim().slice(0,300),at:Date.now()})});
  socket.on("reconnectRoom",({code:c,playerId},done)=>{const r=rooms.get(c),p=r?.players.find(x=>x.id===playerId);if(!r||!p)return done({ok:false}); p.id=socket.id;p.connected=true;p.disconnectedAt=undefined;const key=`${r.code}:${playerId}`,timer=disconnectTimers.get(key);if(timer){clearTimeout(timer);disconnectTimers.delete(key)}if(r.hostId===playerId)r.hostId=socket.id;r.pieces.forEach(x=>{if(x.owner===playerId)x.owner=socket.id});if(r.rematchVotes)r.rematchVotes=r.rematchVotes.map(id=>id===playerId?socket.id:id);socket.join(c);sessions.set(socket.id,{room:c,player:socket.id});done({ok:true,code:c});publish(r)});
  socket.on("disconnect",()=>{const s=sessions.get(socket.id),r=s&&rooms.get(s.room);if(r)markDisconnected(r,socket.id)});
}); const port=Number(process.env.PORT ?? 3001); http.listen(port,"0.0.0.0",()=>console.log(`Yut server: http://localhost:${port}`));
